### ISSUE TITLE
How do you turn this on ?

### ISSUE THREAD

**Issue by harerama** [rmcgirr83/sfpo#1]
Hello,

I have enabled the extension, but I can't find the way to turn the feature on.
I was expecting a section in the "Extensions" section, but nothing shows up.
Is it hidden somewhere else ?

Thanks

**Comment by bissim** [comment]
~~It is a user permission, there is no setting in _Extensions_ section.~~
Nevermind, I misread.

**Comment by harerama** [comment]
Of course, after 20 minutes of searching, I decided to post here, and just after that, I found it...
For the record, go to "Forums"/"Manage Forums" and edit the a Forum (not a category...), then the option is Enable show first post only to guest

**Comment by rmcgirr83** [comment]
Readme updated
